    name: Deploy to Hugging Face Space

    on:
      push:
        branches:
          - main # or your default branch

    jobs:
      deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Push to Hugging Face Space
            env:
              HF_TOKEN: ${{ secrets.HF_TOKEN }}
            run: |
              git config --global user.email "rahimwazir166@gmail.com"
              git config --global user.name "rahimnadan"
              git remote add space https://HF_USERNAME:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Abdur123/alwasaet-rag
              git push --force space main # or your default branch
