name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Git LFS
        run: |
          git lfs install

      - name: Configure Git
        run: |
          git config --global user.email "rahimwazir166@gmail.com"
          git config --global user.name "rahimnadan"

      - name: Sync with Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Remove any existing space remote
          git remote remove space 2>/dev/null || true
          
          # Add Hugging Face Space remote
          git remote add space https://Abdur123:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Abdur123/alwasaet-rag
          
          # Fetch the remote to understand the differences
          git fetch space main
          
          # Option 1: Merge strategy (preserves HF Space history)
          git merge space/main --allow-unrelated-histories -X ours --no-edit || true
          
          # Push the merged result
          git push space main
